name: 'ZC Copy Content - Paragraph'
description: 'Installs Copy Component Paragraph'
type: 'Feature'

recipes:
  - zr-cke5-recipe
  - zr-paragraph-bundle
install:
  - color_field
config:
  strict: false